/*
 * Copyright 2010-2021 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.konan.blackboxtest;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link GenerateNewCompilerTests.kt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("native/tests-blackbox/testData/blackbox")
@TestDataPath("$PROJECT_ROOT")
public class NativeBlackBoxTestGenerated extends AbstractNativeBlackBoxTest {
    @Test
    public void testAllFilesPresentInBlackbox() throws Exception {
        KtTestUtil.assertAllTestsPresentInSingleGeneratedClassWithExcluded(this.getClass(), new File("native/tests-blackbox/testData/blackbox"), Pattern.compile("^(.+)\\.kt$"), null);
    }

    @Test
    @TestMetadata("sample/regular_custom_args.kt")
    public void testSample_Regular_custom_args() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/regular_custom_args.kt");
    }

    @Test
    @TestMetadata("sample/regular_multifile.kt")
    public void testSample_Regular_multifile() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/regular_multifile.kt");
    }

    @Test
    @TestMetadata("sample/regular_simple.kt")
    public void testSample_Regular_simple() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/regular_simple.kt");
    }

    @Test
    @TestMetadata("sample/regular_simple_explicit_mode.kt")
    public void testSample_Regular_simple_explicit_mode() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/regular_simple_explicit_mode.kt");
    }

    @Test
    @TestMetadata("sample/regular_simple_with_output.kt")
    public void testSample_Regular_simple_with_output() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/regular_simple_with_output.kt");
    }

    @Test
    @TestMetadata("sample/standalone_multifile.kt")
    public void testSample_Standalone_multifile() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/standalone_multifile.kt");
    }

    @Test
    @TestMetadata("sample/standalone_notr_multifile_entry_point.kt")
    public void testSample_Standalone_notr_multifile_entry_point() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/standalone_notr_multifile_entry_point.kt");
    }

    @Test
    @TestMetadata("sample/standalone_notr_simple.kt")
    public void testSample_Standalone_notr_simple() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/standalone_notr_simple.kt");
    }

    @Test
    @TestMetadata("sample/standalone_notr_simple2.kt")
    public void testSample_Standalone_notr_simple2() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/standalone_notr_simple2.kt");
    }

    @Test
    @TestMetadata("sample/standalone_notr_simple_entry_point.kt")
    public void testSample_Standalone_notr_simple_entry_point() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/standalone_notr_simple_entry_point.kt");
    }

    @Test
    @TestMetadata("sample/standalone_notr_simple_entry_point2.kt")
    public void testSample_Standalone_notr_simple_entry_point2() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/standalone_notr_simple_entry_point2.kt");
    }

    @Test
    @TestMetadata("sample/standalone_notr_simple_with_input_and_output.kt")
    public void testSample_Standalone_notr_simple_with_input_and_output() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/standalone_notr_simple_with_input_and_output.kt");
    }

    @Test
    @TestMetadata("sample/standalone_notr_simple_with_output.kt")
    public void testSample_Standalone_notr_simple_with_output() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/standalone_notr_simple_with_output.kt");
    }

    @Test
    @TestMetadata("sample/standalone_simple.kt")
    public void testSample_Standalone_simple() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/standalone_simple.kt");
    }

    @Test
    @TestMetadata("sample/standalone_simple_with_output.kt")
    public void testSample_Standalone_simple_with_output() throws Exception {
        runTest("native/tests-blackbox/testData/blackbox/sample/standalone_simple_with_output.kt");
    }
}
